### ISSUE TITLE
API

### ISSUE THREAD

**Issue by creeperplayer20** [theohdg2/Economy#1]
Hello, I need help with your API.

I need to see players money, add or reduce money.

**Comment by achedon12** [comment]
Hello/Good evening, I have just added the command to see the players' currency. 
Please delete the plugin in the 'plugin_data' folder as well as in 'plugin' and reinstall it!

**Comment by achedon12** [comment]
Good evening/Hello, just do Economy::getInstance()->reduceMoney() or  Economy::getInstance()->getMoney() or  Economy::getInstance()->addMoney()
Hoping to have answered you as soon as possible
